title: Umbrarose's Adventures in Software Development
email: wwwwolf@iki.fi
description: >-
  Random code thingies from a weird developer called Rose. These can get
  sorta unusual and stuff.
domain: umbraroze.github.io
baseurl: /
url: https://umbraroze.github.io
github_username: umbraroze
show_downloads: false

collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:title:output_ext

# Build settings
# For remote theme documentation: https://github.com/pages-themes/cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed

